---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.64.10
    path: "/home/www/binderhub"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.64.10
    path: "/home/www/binderhub/shared"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
